name: Different variant of a reference
description: Submit a different version of one of the references cited in this project
labels:
    - "alt_reference"
body:
    - type: markdown
      attributes:
        value: |
          When submitting an alternate version of source/reference/document:
          - check that it has not already been submitted in another open or closed [issue](https://github.com/coffinproblems/resources/issues?q=is%3Aissue) or [pull request](https://github.com/coffinproblems/resources/pulls?q=is%3Apr);
          - provide as many details as possible on this alternate version;
          - describe the differences, if known, compared to the version(s) of the document already cited in this project;
          - provide a link to the reference, if possible, and/or other details on where/how to consult it.

    - type: textarea
      id: reference
      attributes:
        label: Reference
        description: Cite the reference, accompanied with as much information as possible.
      validations:
        required: true

    - type: textarea
      id: link
      attributes:
        label: Links
        description: Include links to online webpages or archives in which the document can be found, if any.
      validations:
        required: false

    - type: textarea
      id: additionalinfo
      attributes:
        label: Additional information
        description: Any additional information that may be useful.
      validations:
        required: false

    - type: textarea
      id: files
      attributes:
        label: Files
        description: Attach here scans or images of the document (or any other useful files), if any.
      validations:
        required: false
