name: New reference
description: Submit a relevant reference not already cited in this project
labels:
    - "new_reference"
body:
    - type: markdown
      attributes:
        value: |
          When submitting a new source/reference/document:
          - verify that it is not already cited by the latest version of this project;
          - check that it has not already been submitted in another open or closed [issue](https://github.com/coffinproblems/resources/issues?q=is%3Aissue) or [pull request](https://github.com/coffinproblems/resources/pulls?q=is%3Apr);
          - provide as many details as possible, such as the author(s), title, publishing date, etc.;
          - provide a link to the reference, if possible, and/or other details on where/how to consult it;
          - if multiple versions of the document are available, mention all of them, even if they do not appear to have any differences;
          - if the document is not readily available online, consider submitting it in file attachments, if it is possible to do so.

    - type: textarea
      id: reference
      attributes:
        label: Reference
        description: Provide the reference, along with as much information as possible, such as the author(s), title, publishing date, etc.
      validations:
        required: true

    - type: textarea
      id: link
      attributes:
        label: Links
        description: Include links to online webpages or archives in which the document can be found, if any.
      validations:
        required: false

    - type: textarea
      id: additionalinfo
      attributes:
        label: Additional information
        description: Any additional information that may be useful.
      validations:
        required: false

    - type: textarea
      id: files
      attributes:
        label: Files
        description: Attach here scans or images of the document (or any other useful files), if any.
      validations:
        required: false
