name: Build ebook


on:
  workflow_call:
    inputs:

      texlive_digest:
        required: true
        type: string

      timestamp:
        required: true
        type: string

      directory:
        required: true
        type: string

      filename:
        required: true
        type: string


jobs:

  build:
    name: Generate EPUB document for ${{ inputs.directory }}${{ inputs.filename }}

    runs-on: ubuntu-latest
    container:
      image: texlive/texlive@${{ inputs.texlive_digest }}
    defaults:
      run:
        working-directory: ./src/${{ inputs.directory }}
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Directory name
        run: |
          path=${{ inputs.directory }}
          echo "dirname=$(basename "$path")" >> $GITHUB_ENV

      - name: Build ${{ env.dirname }}${{ inputs.filename }} as ebook with MathML formulas
        id: build_mathml
        env:
          SOURCE_DATE_EPOCH: ${{ inputs.timestamp }}
          FORCE_SOURCE_DATE: 1
        run: |
          shopt -s nullglob
          for main_file in main*.tex; do
              if [[ -f "$main_file" ]]; then
                  # Extract suffix between 'main' and '.tex'
                  suffix="${main_file#main}"
                  suffix="${suffix%.tex}"
                  tex4ebook --build-dir "./build_mathml${suffix}" --output-dir ./output --jobname "${{ env.dirname }}${{ inputs.filename }}${suffix}-mathml" -f epub3 "${main_file}" mathml
              fi
          done

      - name: Build ${{ env.dirname }}${{ inputs.filename }} as ebook with SVG formulas
        id: build_svg
        env:
          SOURCE_DATE_EPOCH: ${{ inputs.timestamp }}
          FORCE_SOURCE_DATE: 1
        run: |
          shopt -s nullglob
          for main_file in main*.tex; do
              if [[ -f "$main_file" ]]; then
                  # Extract suffix between 'main' and '.tex'
                  suffix="${main_file#main}"
                  suffix="${suffix%.tex}"
                  tex4ebook --build-dir "./build_svg${suffix}" --output-dir ./output --jobname "${{ inputs.filename }}${suffix}-svg" -f epub "${main_file}" svg
              fi
          done

      - name: Upload logs of ebook builds
        uses: actions/upload-artifact@v7
        with:
          name: build-ebook-logs-${{ env.dirname }}${{ inputs.filename }}
          path: src/${{ inputs.directory }}/build_*/*.log

      - name: Upload ebooks of ${{ env.dirname }}${{ inputs.filename }}
        uses: actions/upload-artifact@v7
        with:
          name: ebook-${{ env.dirname }}${{ inputs.filename }}
          path: src/${{ inputs.directory }}/output/${{ env.dirname }}${{ inputs.filename }}*.epub
